import '../../styles/globals.css'

import React, { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout: React.FC<PropsWithChildren<{}>> = ({ children }) => {
  return (
    <html lang="en">
      <body className="bg-background">{children}</body>
    </html>
  );
};

export default RootLayout;
