CA 1:
  l'avenir: the future
  une amélioration: an improvement
  un archipel: an archipalego
  un conseil: a piece of advice
  un déplacement: a move
  le chemin de fer: the railroad
  un/e comptable: an accountant
  compter: to count
  une décision: a décision
  décisif/décisive: decisive
  indécis/e: indecisive
  déménager: to move (houses)
  ensigner: to teach
  un ensignant / une ensignante: a teacher
  un éventail: "a fan (figurative: a range of ...)"
  un/e gérontologe: a gerentologist
  outer-mer: overseas
  la pauvreté: the poverty
  un pauvre / une pauvresse: a poor person
  appauvrir: to impoverish
  s'appauvrir: to become poor
  pauvre: poor
  un prêt: a loan
  prêter: to loan
  la richesse: a rich person
  enrichir: to enrich
  riche: rich
  un salaire: a salary

RESPIRE:
  approcher: to approach
  proche: close
  gamin/e (familier): child (informal)
  avancer: to advance
  un chemin: a path
  débarque: to land
  les souliers: the shoes
  la gueule: the mouth (of an animal)
  la veille: the previous night
  bouffer: to éventail
  le milieu: the center
  en plein [qch]: in the middle of [sth]
  un con / une conne: an idiot
  tout bas: very quietly
  l'epoque: the era
  allonger: to extend
  le pire: the worst
  un/e escalve: a slave
  à moitié: half
  une défroque: rag, old rag
  cent pour cent: one hundred percent
  un chou: a cabbage
  plutôt: instead
  plutôt que [qch]: rather than [sth]
  un trou: a hole
  une fosse à purin: a manure pit

Niveau 13-ab Initio/Langue B/Vocabulaire - L'environnement LABergerman-2122:
  des inondations: some floods 
  la circulation routière: the road traffic
  la déforestation: the deforestation
  la fonte des glaciers: the melting of the Ice
  la pollution la propreté: the pollution
  la propreté: the cleanliness
  la saleté: the dirtiness 
  la sécheresse: the drought
  les émissions de gaz: the gas emissions
  les émissions toxiques: the toxic emissions
  les énergies renouvelables: the renewable energy
  les ordures ménagères: the household wastes
  les tempêtes: the storms
  une marée noire: an oil slick 
  une répercussion: a knock-on effect
  des canicules: some heat waves
  l'effet de serre: the greenhouse effect
  le boisement: the reforestation
  le bruit: the noise
  le bruit autour des aéroports : the noise around airports
  le dérèglement climatique : the climate change
  le lampadaire: the lampost
  le réchauffement de la terre: the changing of the earth's temperature
  le recyclage des déchets ménagers/ordures ménagères : the recycling of household waste 
  le tri sélectif: the selective recycling 
  le trou dans la couche d'ozone: the hole in the ozone layer
  les gestes écologiques: the ecological actions
  les ouragans: the hurricanes
  les produits chimiques: the chemical products
  l'énergie solaire/éolienne/hydraulique: the energy solar/wind/water
  la centrale nucléaire: a nuclear power plant
  la croissance : the growth/development 
  la disparition/l'extinction de certains animaux: the extinction of animals
  la pollution atmosphérique a un effet nocif: the pollution of the atmosphere has a harmful effect
  la pollution lumineuse: the light pollution
  la surpopulation humalne: the human over population
  la production coûteuse: the expensive production 
  les boîtes de conserve: the tin cans
  les épluchures : the fruit skins
  une centrale électronique/nucléaire : an electric/nuclear powerplant
  une ère: an era
  des plats cuisinés: some ready-made meals
  du gaz carbonique: the carbon gas
  l'épuisement : the running out
  le charbon: the coal
  le micro-ondes: the microwave
  les emballages: the packaging
  les poumons: the lungs
  mon panier: my basket
  les ailments: the foods
  les chauffages: the heating
  les combustibles fossiles: the fossil fuels
  les déchets / les ordures ménagères: the household wastes
  un égout: a sewer
  un fleuve: a big river
  un naufrage: a shipwreck
  un navire: a ship
  un pétrolier: a petrol ship
  avoir un impact sur la biodiversité: the have an impact on
  dégrader le paysage: to degrade the landscape
  développer les énergies renouvelables: to develop renewable energy
  émettre des...: to emit...
  émettre du carbone: to emit carbon
  éteindre: to switch off
  éteindre la lumière: to switch off the light
  faire du covoiturage gâcher: to carpool 
  gâcher: to ruin/spoil
  gâcher le paysage: to spoil the landscape
  gaspiller l'énergie: to waste energy
  inciter le public à changer de comportement: to encourage people to change their behavior
  J'essaie d'éviter les emballages: try to avoid the packaging
  jeter: to throw away
  polluer: to pollute
  polluer l'atmosphère: to pollute the atmosphere.
  produire des gaz à effet de serre: to produce greenhouse gases
  provoquer des maladies physiques / psychologiques: to provoke physical / psychological sickness
  provoquer le cancer: to provoke the cancer
  s'amenuiser: to diminish/run out
  s'épuiser: to run out
  s'inflitrer: to infiltrate
  salir: to dirty
  sauvegarder: to preserve
  se déverser: to wash out
  se mettre d'accord: to agree
  se répandre: to spread/spill into
  sensibiliser les consommateurs aux problèmes de l'environnement: to inform the consumers of environmental problems
  subir un mauvais traitement: to undergo bad treatment
  subir une opération chirurgicale: to undergo surgical treatment
  écolo: ecofriendly
  émis (participe passé): emitted
  en voie d'extinction: endangered
  ils sont menacés: they are threatened
  nocif/nocive = nuisible: harmful 
  pollué: polluted
  propre: clean
  sale: dirty
  il s'agit de: it is about
  en effet / effectivement: indeed, even, in fact
  voire: indeed, even, in fact
